[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
loan = [
    "${USDT}",
    "${USD1}"
]

collateral = [
    "${WBNB}",
    "${BTCB}"
]

oracle = [
    "${MULTI_ORACLE}",
    "${MULTI_ORACLE}"
]

irm = [
    "${IRM}",
    "${ALPHA_IRM}"
]

[bsc.uint]
lltv = [
    "${LLTV_33}",
    "${LLTV_33}"
]
