[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
loan = [
    "${U}",
    "${USDT}",
    "${USD1}",
    "${USDT}",
    "${USD1}",
    "${U}",
    "${USDT}"
]

collateral = [
    "${USDC}",
    "${USDC}",
    "${USDC}",
    "${USDC_USDT}",
    "${USDC_USDT}",
    "${USDC_USDT}",
    "${wNLPUSDT}"
]

oracle = [
  "${MULTI_ORACLE}",
  "${MULTI_ORACLE}",
  "${MULTI_ORACLE}",
  "${USDC_USDT_SmartProvider}",
  "${USDC_USDT_SmartProvider}",
  "${USDC_USDT_SmartProvider}",
  "${MULTI_ORACLE}"
]

irm = [
    "${IRM}",
    "${IRM}",
    "${IRM}",
    "${IRM}",
    "${IRM}",
    "${IRM}",
    "${IRM}"
]

[bsc.uint]
lltv = [
    "${LLTV_965}",
    "${LLTV_965}",
    "${LLTV_965}",
    "${LLTV_965}",
    "${LLTV_965}",
    "${LLTV_965}",
    "${LLTV_965}"
]
