[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
loan = [
    "${USDT}",
    "${USD1}"
]

collateral = [
    "${WBNB}",
    "${BTCB}"
]

oracle = [
    "${MULTI_ORACLE}",
    "${MULTI_ORACLE}"
]

irm = [
    "${IRM}",
    "${ALPHA_IRM}"
]

ptCollateral = [
  "${ptsUSDe09APR2026Plasma}",
  "${ptsUSDe09APR2026Plasma}",
  "${ptsUSDe09APR2026Plasma}"
]

ptLoan = [
  "${USD1}",
  "${USDT}",
  "${U}"
]

ptOracle = [
  "${ptsUSDe09APR2026PlasmaBaseOracle}",
  "${ptsUSDe09APR2026PlasmaBaseOracle}",
  "${ptsUSDe09APR2026PlasmaBaseOracle}"
]

multiOracle = "${MULTI_ORACLE}"

admin = "${ADMIN}"

[bsc.uint]
lltv = [
    "${LLTV_33}",
    "${LLTV_33}"
]
