[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
loan = [
  "${USD1}",
  "${USDT}",
  "${U}",
]

collateral = [
  "${ptSrUSDe02APR2026}",
  "${ptSrUSDe02APR2026}",
  "${ptSrUSDe02APR2026}",
]

oracle = [
  "${ptSrUSDe02APR2026USD1Oracle}",
  "${ptSrUSDe02APR2026USDTOracle}",
  "${ptSrUSDe02APR2026UOracle}",
]

irm = [
  "${IRM}",
  "${IRM}",
  "${IRM}",
]

ptCollateral = [
  "${ptSrUSDe02APR2026}",
  "${ptSrUSDe02APR2026}",
  "${ptSrUSDe02APR2026}"
]

ptLoan = [
  "${USD1}",
  "${USDT}",
  "${U}"
]

ptOracle = [
  "${ptSrUSDe02APR2026BaseOracle}",
  "${ptSrUSDe02APR2026BaseOracle}",
  "${ptSrUSDe02APR2026BaseOracle}"
]

multiOracle = "${MULTI_ORACLE}"

admin = "${ADMIN}"

[bsc.uint]
lltv = [
  "${LLTV_90}",
  "${LLTV_90}",
  "${LLTV_90}",
]
