[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
loan = [
    "${USD1}",
    "${USDT}",
    "${U}"
]

collateral = [
    "${ptsUSDe09APR2026Plasma}",
    "${ptsUSDe09APR2026Plasma}",
    "${ptsUSDe09APR2026Plasma}"
]

oracle = [
    "${ptsUSDe09APR2026PlasmaUSD1Oracle}",
    "${ptsUSDe09APR2026PlasmaUSDTOracle}",
    "${ptsUSDe09APR2026PlasmaUOracle}"
]

irm = [
    "${IRM}",
    "${IRM}",
    "${IRM}"
]

ptCollateral = [
  "${ptsUSDe09APR2026Plasma}",
  "${ptsUSDe09APR2026Plasma}",
  "${ptsUSDe09APR2026Plasma}"
]

ptLoan = [
  "${USD1}",
  "${USDT}",
  "${U}"
]

ptOracle = [
  "${ptsUSDe09APR2026PlasmaBaseOracle}",
  "${ptsUSDe09APR2026PlasmaBaseOracle}",
  "${ptsUSDe09APR2026PlasmaBaseOracle}"
]

multiOracle = "${MULTI_ORACLE}"

admin = "${ADMIN}"

[bsc.uint]
lltv = [
    "${LLTV_945}",
    "${LLTV_945}",
    "${LLTV_945}"
]
