[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
loan = [
    "${USD1}",
    "${USDT}",
    "${U}",
]

collateral = [
    "${ptUSDe07May2026}",
    "${ptUSDe07May2026}",
    "${ptUSDe07May2026}",
]

oracle = [
  "${ptUSDe07May2026USD1Oracle}",
  "${ptUSDe07May2026USDTOracle}",
  "${ptUSDe07May2026UOracle}",
]

irm = [
    "${IRM}",
    "${IRM}",
    "${IRM}",
]

ptCollateral = [
  "${ptSrUSDe02APR2026}",
  "${ptSrUSDe02APR2026}",
  "${ptSrUSDe02APR2026}"
]

ptLoan = [
  "${USD1}",
  "${USDT}",
  "${U}"
]

ptOracle = [
  "${ptSrUSDe02APR2026BaseOracle}",
  "${ptSrUSDe02APR2026BaseOracle}",
  "${ptSrUSDe02APR2026BaseOracle}"
]

multiOracle = "${MULTI_ORACLE}"

admin = "${ADMIN}"

[bsc.uint]
lltv = [
    "${LLTV_945}",
    "${LLTV_945}",
    "${LLTV_945}",
]
