[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
### Tokens
tokens = [
    "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
    "0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c",
    "0x4aae823a6a0b376De6A78e74eCC5b079d38cBCf7",
    "0xb84cEC1Ab2af11b530ae0d8594B1493556be49Cd",
    "0x8d0D000Ee44948FC98c9B98A4FA4921476f08B0d",
    "0xB0b84D294e0C75A6abe60171b70edEb2EFd14A1B",
    "0x2170Ed0880ac9A755fd29B2688956BD959F933F8",
    "0x55d398326f99059fF775485246999027B3197955",
    "0xDD809435ba6c9d6903730f923038801781cA66ce",
    "0x5A110fC00474038f6c02E89C707D638602EA44B5",
    "0x917AF46B3C3c6e1Bb7286B9F59637Fb7C65851Fb",
    "0x26c5e01524d2E6280A48F2c50fF6De7e52E9611C",
    "0xa2E3356610840701BDf5611a53974510Ae27E2e1",
    "0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34",
    "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2",
    "0x80137510979822322193FC997d400D5A6C747bf7",
    "0x87d00066cf131ff54B72B134a217D5401E5392b6",
    "0xf3527ef8dE265eAa3716FB312c12847bFBA66Cef",
    "0x7788A3538C5fc7F9c7C8A74EAC4c898fC8d87d92",
    "0x2492D0006411Af6C8bbb1c8afc1B0197350a79e9",
    "0x37fbFfE3a305E342c2cd00929A904e971c65Bafd",
    "0x0782b6d8c4551B9760e74c0545a9bCD90bdc41E5",
    "0x64274835D88F5c0215da8AADd9A5f2D2A2569381",
    "0x95034f653D5D161890836Ad2B6b8cc49D14e029a",
    "0x6bdcCe4A559076e37755a78Ce0c06214E59e4444",
    "0x783c3f003f172c6Ac5AC700218a357d2D66Ee2a2",
    "0x1346b618dC92810EC74163e4c27004c921D446a5",
    "0xB901c7A2D2Bc05D8B7e7eE4F7Fcf72CAaABd2F49",
    "0xf307910A4c7bbc79691fD374889b36d8531B08e3",
    "0x607C834cfb7FCBbb341Cbe23f77A6E83bCf3F55c",
    "0x1A9Fd6eC3144Da3Dd6Ea13Ec1C25C58423a379b1",
    "0x647A50540F5a1058B206f5a3eB17f56f29127F53",
    "0xB035723D62e0e2ea7499D76355c9D560f13ba404",
    "0xf4B385849f2e817E92bffBfB9AEb48F950Ff4444",
    "0xd76Ec0A96eAffe1cCa33313352dEdA1CD3Cfa7EE",
    "0x4254813524695def4163A169e901f3d7a1a55429",
    "0x4772D2e014F9fC3a820C444e3313968e9a5C8121",
    "0x6B2a01A5f79dEb4c2f3c0eDa7b01DF456FbD726a",
    "0x4a3846d069B800343D53e72B80a644Bb496D9aB2",
    "0x31E88bF4AC49EEf6711756D141F1A63E78F9F665",
    "0x47474747477b199288bF72a1D702f7Fe0Fb1DEeA",
    "0x000Ae314E2A2172a039B26378814C252734f556A",
    "0x77734e70b6E88b4d82fE632a168EDf6e700912b6",
    "0xc8739fbBd54C587a2ad43b50CbcC30ae34FE9e34",
    "0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE",
    "0xE747E54783Ba3F77a8E5251a3cBA19EBe9C0E197",
    "0x4809010926aec940b550D34a46A52739f996D75D",
    "0x84575b87395c970F1F48E87d87a8dB36Ed653716",
    "0x6254500243135573A948d7a5F90c307Cd7973f43",
    "0x4F2760B32720F013E900DC92F65480137391199b",
    "0x9be61A38725b265BC3eb7Bfdf17AfDFc9d26C130",
    "0xcE24439F2D9C6a2289F741120FE202248B666666",
    "0xbBD3e74E69e6BDDDA8e5AAdC1460611A8f7cd05a",
    "0x7EB92A12a15E8a019A26A8b344F1e59b14cb8Ad3"
]

### Oracles
oracles = [
    "0xf3afD82A4071f272F403dC176916141f44E6c750",
    "0x9B7FAE34238E37dF77d35559eF62995c066B5e11",
    "0xd69E4BF784185139994eeb3F0Db9Ea307d31FDdB",
    "0x09E664516C91461d8ed58C934Af48048D2534fe9"
]

### IRMs
irms = [
    "0xFe7dAe87Ebb11a7BEB9F534BB23267992d9cDe7c",
    "0x5F9f9173B405C6CEAfa7f98d09e4B8447e9797E6"
]

ptBaseOracles = [
    "0x539FA1ce6333F79a0cda5dEB9833B5fAEEABE70E"
]

wallets = [
    "0x07D274a68393E8b8a2CCf19A2ce4Ba3518735253"
]

[bsc.uint]
### LLTVs
lltvs = [
    330000000000000000,
    500000000000000000,
    600000000000000000,
    700000000000000000,
    750000000000000000,
    800000000000000000,
    850000000000000000,
    860000000000000000,
    865000000000000000,
    900000000000000000,
    915000000000000000,
    945000000000000000,
    965000000000000000
]

[bsc.string]
tokenNames = [
    "WBNB",
    "BTCB",
    "solvBTC",
    "ptClisBNB30Otc",
    "USD1",
    "slisBNB",
    "ETH",
    "USDT",
    "ptSUSDe26JUN2025",
    "USDF",
    "asUSDF",
    "wstETH",
    "wBETH",
    "USDe",
    "sUSDe",
    "STONE",
    "Puffer",
    "USDX",
    "sUSDX",
    "USR",
    "ptUSDe7AUG2025",
    "lisUSD",
    "puffETH",
    "AB",
    "B",
    "B2",
    "xsolvBTC",
    "ptSatUSD11SEP2025",
    "ANKR",
    "ptUSDe30OTC2025",
    "SPA",
    "solvBTC_DLP",
    "OIK",
    "EGL1",
    "ptSigmaLP25Sep2025",
    "wstUSR",
    "yUSD",
    "uniBTC",
    "ptUSR27NOV2025",
    "ptSatUSD18DEC2025",
    "WLFI",
    "Aster",
    "asBNB",
    "mXRP",
    "XRP",
    "Take",
    "wsrUSD",
    "CDL",
    "ptUSDe5FEB2026",
    "sUSD1",
    "AT",
    "U",
    "UUSDT",
    "ptsUSDe09APR2026Plasma"
]

ptBaseOracleNames = [
    "ptsUSDe09APR2026PlasmaBaseOracle"
]

oracleNames = [
    "MULTI_ORACLE",
    "ptsUSDe09APR2026PlasmaUSD1Oracle",
    "ptsUSDe09APR2026PlasmaUSDTOracle",
    "ptsUSDe09APR2026PlasmaUOracle"
]

irmNames = [
    "IRM",
    "ALPHA_IRM"
]

lltvNames = [
    "LLTV_33",
    "LLTV_50",
    "LLTV_60",
    "LLTV_70",
    "LLTV_75",
    "LLTV_80",
    "LLTV_85",
    "LLTV_86",
    "LLTV_865",
    "LLTV_90",
    "LLTV_915",
    "LLTV_945",
    "LLTV_965"
]

walletNames = [
    "ADMIN"
]
